- name: Pip Install Task
  hosts: local
  gather_facts: False

  
  tasks:

    - name: Test SSH Connection
      command : whoami
      register: message
      
    - name: show result
      debug:
        msg: "result: {{message}}"
        
      
