- name: Pip Install Task
  hosts: local
  gather_facts: False

  
  tasks:

    - name: Test SSH Connection
      command : whoami
      register: message
      
    - name: Install ansible pip dependencies for Ansible
      pip:
        name: "{{ item }}"
        state: latest
      register: message
      with_items:        
        - hvac
        - "hvac[parser]"
      
    - name: show result
      debug:
        msg: "result: {{message}}"
        
      
