- name: Test SSH Connection
  hosts: local
  gather_facts: False

  vars_files:
    # 讀取 Ansible Vault 檔案
    - test.yml   

  tasks:
  
    - name: Print debug message
      debug:        
        msg: "user:{{username}}"



