- name: Test SSH Connection
  hosts: local
  gather_facts: False

  vars_files:
    - test.yml
    - test1.yml
    

  tasks:

    - name: Test SSH Connection
      ping:
      register: message

    - name: Print debug message
      debug:
        msg: "ansible_vault:{{ansible_vault}} message:{{message}} and user:{{username}}"



